spring:
  batch:
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:h2:mem:db;MODE=MYSQL;
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true